[package]
name = "riki"
version = "0.1.0"
authors = ["Daniel Parks <oss-riki@demonhorse.org>"]
description = "Simple server for almost-static websites"
homepage = "https://github.com/danielparks/riki"
repository = "https://github.com/danielparks/riki"
documentation = "https://github.com/danielparks/riki"
readme = "README.md"
exclude = [".*", "/release.sh"]
keywords = []
categories = []                                       # https://crates.io/category_slugs
license = "MIT OR Apache-2.0"
edition = "2024"
rust-version = "1.88"

[package.metadata.docs.rs]
all-features = true
rustdoc-args = ["--cfg", "docsrs"]

[[bin]]
name = "riki"
path = "src/cli/main.rs"

[dependencies]
actix-files = "0.6.10"
actix-http = "3.11.0"
actix-web = "4.11.0"
ambassador = "0.5.0"
anyhow = "1.0.95"
base64 = "0.22.1"
clap = { version = "4.5.27", features = ["derive"] }
derive_more = { version = "2.1.1", features = ["from", "display"] }
dom_query = "0.24.0"
globset = "0.4.18"
handlebars = { version = "6.3.2", features = ["dir_source", "rust-embed"] }
htmlize = "1.0.6"
jiff = { version = "0.2.15", features = ["serde"] }
maplit = "1.0.2"
mime = "0.3.17"
pulldown-cmark = "0.13.0"
read-doc = "0.1.0"
regex = "1.11.1"
rust-embed = "8.7.2"
serde = { version = "1.0.219", features = ["derive"] }
serde_json = "1.0.143"
serde_yaml = "0.9.34"
strum = { version = "0.27.2", features = ["derive"] }
tendril = "0.4.3"
termcolor = "1.4.1"
thiserror = "2.0.15"
tracing = "0.1.41"
tracing-actix-web = "0.7.19"
tracing-subscriber = { version = "0.3.20", features = ["chrono", "env-filter"] }
url = "2.5.7"

[dev-dependencies]
actix-http = "3.11.0"
assert2 = "0.3.16"
temp-dir = "0.1.16"
test-log = { version = "0.2.19", default-features = false, features = ["color", "trace"] }
tracing-test = "0.2.5"

[lints]
workspace = true

[workspace.lints.rust]
unsafe_code = "forbid"
missing_docs = "warn"

[workspace.lints.clippy]
nursery = { level = "warn", priority = -1 }
pedantic = { level = "warn", priority = -1 }
missing_docs_in_private_items = "warn"

# Other restriction lints
allow_attributes = "warn"
allow_attributes_without_reason = "warn"
arithmetic_side_effects = "warn"
as_underscore = "warn"
assertions_on_result_states = "warn"
dbg_macro = "warn"
default_union_representation = "warn"
empty_structs_with_brackets = "warn"
filetype_is_file = "warn" # maybe?
fn_to_numeric_cast_any = "warn"
format_push_string = "warn" # maybe? alternative is fallible.
get_unwrap = "warn"
impl_trait_in_params = "warn"
integer_division = "warn"
lossy_float_literal = "warn"
mem_forget = "warn"
mixed_read_write_in_expression = "warn"
multiple_inherent_impl = "warn"
multiple_unsafe_ops_per_block = "warn"
mutex_atomic = "warn"
rc_buffer = "warn"
rc_mutex = "warn"
same_name_method = "warn"
semicolon_inside_block = "warn"
str_to_string = "warn"
undocumented_unsafe_blocks = "warn"
unnecessary_safety_doc = "warn"
unnecessary_self_imports = "warn"
unneeded_field_pattern = "warn"
verbose_file_reads = "warn"

# Pedantic exceptions
let_underscore_untyped = "allow"
manual_string_new = "allow"
map_unwrap_or = "allow"
module_name_repetitions = "allow"
unnecessary_debug_formatting = "allow" # display() doesn’t escape invalid chars

# Nursery exceptions
option_if_let_else = "allow"
