[package]
name = "rustwiki"
version = "0.1.0"
authors = ["Daniel Parks <dp+git@oxidized.org>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
mustache = "0" # Look at ramhorns instead of mustache?
pulldown-cmark = { version = "0", default-features = false, features = ["simd"] } # enable simd only on 86_x64?
structopt = "0"
serde = { version = "1.0", features = ["derive"] }
thiserror = "1.0"

# serde_yaml = "0.8"
serde_yaml = { git = "file:///Users/daniel/projects/third-party/serde-yaml", branch = "crate_pub_errorimpl" }

# Bugs: https://github.com/rust-lang/regex/pull/628
#regex = "1"
regex = { git = "https://github.com/danielparks/regex.git", branch = "split_627_and_521" }
