[package]
name = "rustwiki"
version = "0.1.0"
authors = ["Daniel Parks <dp+git@oxidized.org>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
actix-files = "0.5"
actix-web = "3"
anyhow = "1"
htmlize = "0"
lazy_static = "1"
mustache = "0" # Look at ramhorns instead of mustache?
pulldown-cmark = { version = "0", default-features = false, features = ["simd"] } # enable simd only on 86_x64?
regex = "1"
serde = { version = "1", features = ["derive"] }
serde_yaml = "0"
simplelog = "0"
structopt = "0"
thiserror = "1"

[dev-dependencies]
temp_testdir = "0"
