/ {
    # Set the file system directory to look in
    root="/srv/website"

    *.{md,markdown} { # Don’t allow access to page source
        error(403)
    }

    .foo error(403)

    /templates { \
        error(403)#Don’t allow access to templates
    }

    \

    /test-quotes 'test#test'
    /test-quotes2 literal('test#test')

    render(markdown("$clean_path.md"))
    "$clean_path"
    error(404)
}
