//! Errors returned by the crate.

use crate::actions::Source;
use std::ffi::OsString;
use std::io;
use std::path::PathBuf;
use std::result;
use std::string::FromUtf8Error;
use thiserror::Error; // doesn’t conflict with the enum.

/// Error type for the crate.
#[derive(Debug, Error)]
pub enum Error {
    /// Failed to bind to socket
    #[error("Error binding to socket on {address:?}: {source}")]
    BindError {
        /// The original error
        source: io::Error,

        /// The address the socket could not bind on
        address: String,
    },

    /// IO error
    #[error("Error in IO: {0}")]
    Io(#[from] io::Error),

    /// An important directory is missing
    #[error("Missing directory {0:?}")]
    MissingDirectory(PathBuf),

    /// Failed to render page body in a template with [`handlebars`]
    #[error("{source}")]
    TemplateRender {
        /// The original error.
        source: handlebars::RenderError,

        /// The source of the page.
        ///
        /// Boxed to prevent the error type from getting too big.
        page_source: Box<Source>,
    },

    /// Failed to parse page metadata
    #[error("Error parsing page metadata: {0}")]
    ParsePageMetadata(#[from] serde_yaml::Error),

    /// Failed to read page file
    #[error("Error reading page file {path:?}: {source}")]
    ReadPageFile {
        /// The original error
        source: io::Error,

        /// The page file
        path: PathBuf,
    },

    /// Failed to compile template with [`handlebars`]
    #[error(transparent)]
    TemplateCompile(#[from] handlebars::TemplateError),

    /// File was too large to load into memory
    #[error("File ({0:?}) was too large to load into memory")]
    FileTooLarge(PathBuf),

    /// Could not convert binary data to UTF-8
    #[error("Found non-UTF-8 data")]
    NotUtf8(#[from] NotUtf8),

    /// Request path did not start with '/'
    #[error("Request path {0:?} did not start with '/'")]
    RequestPathNotAbsolute(String),

    /// Request path contained ".." segment
    #[error("Request path {0:?} contained \"..\" segment")]
    RequestPathContainsDotDot(String),
}

impl From<FromUtf8Error> for Error {
    #[inline]
    fn from(error: FromUtf8Error) -> Self {
        NotUtf8::from(error).into()
    }
}

impl From<OsString> for Error {
    #[inline]
    fn from(invalid: OsString) -> Self {
        NotUtf8::OsString(invalid).into()
    }
}

/// Encapsulates non-UTF-8 errors.
#[derive(Debug, Error)]
pub enum NotUtf8 {
    /// [`FromUtf8Error`] generated by [`String::from_utf8()`].
    #[error("Found non-UTF-8 data")]
    FromUtf8Error(#[from] FromUtf8Error),

    /// Generated by [`OsString::into_string()`].
    #[error("Found non-UTF-8 data")]
    OsString(OsString),
}

impl From<OsString> for NotUtf8 {
    fn from(invalid: OsString) -> Self {
        Self::OsString(invalid)
    }
}

/// `Result` type for this crate.
pub type Result<T, E = Error> = result::Result<T, E>;
