//! # Serve pages over HTTP
//!
//! How pages are served are determined by a sequence of rules. See
//! [`riki::rules`][crate::rules].

mod tests;

use crate::actions;
use crate::config::SourcedConfiguration;
use crate::config::parser2::Source;
use crate::render::{TemplatesManager, base_templates};
use axum::extract::State;
use axum::response::Response;
use std::fmt;
use std::net::{IpAddr, Ipv4Addr, Ipv6Addr, SocketAddr};
use std::sync::Arc;
use tokio::net;
use tower_http::trace::TraceLayer;

// TODO better error handling
//      - Bad page metadata errors should be shown to admin, but not user
//      - dev mode

/// Main entry point for serving over HTTP.
///
/// `configuration` may either be owned, generated by building up action
/// structures, or parsed from `'static` memory.
///
/// # Errors
///
/// May return an error if the server could not start correctly.
pub async fn serve<S: Source + Sync, A: AsRef<str>>(
    configuration: SourcedConfiguration<S>,
    bind: A,
) -> crate::Result<()> {
    let bind = bind.as_ref();
    for address in net::lookup_host(bind).await? {
        tracing::info!(
            "Listening on {address} (access: http://{})",
            access_address(address)
        );
    }

    axum::serve(
        tokio::net::TcpListener::bind(bind).await.map_err(|error| {
            crate::Error::BindError { source: error, address: bind.to_owned() }
        })?,
        init_app(configuration),
    )
    .await
    .map_err(crate::Error::Io)
}

/// Get the IP:PORT to access the web server on.
///
/// This returns its parameter unless it’s passed an unspecified IP (e.g.,
/// 0.0.0.0), in which case it changes the IP to localhost.
const fn access_address(address: SocketAddr) -> SocketAddr {
    if address.ip().is_unspecified() {
        SocketAddr::new(
            if address.ip().is_ipv4() {
                IpAddr::V4(Ipv4Addr::LOCALHOST)
            } else {
                IpAddr::V6(Ipv6Addr::LOCALHOST)
            },
            address.port(),
        )
    } else {
        address
    }
}

/// Initialize the Axum app to be served.
pub fn init_app<S: Source + Sync>(
    configuration: SourcedConfiguration<S>,
) -> axum::Router {
    axum::Router::new()
        .fallback(axum::routing::get(get_handler))
        .with_state(Arc::new(Router::from_configuration(configuration)))
        .layer(TraceLayer::new_for_http())
}

/// Handle all GET requests
async fn get_handler<S: Source + Sync>(
    State(router): State<Arc<Router<S>>>,
    request: axum::extract::Request,
) -> Response {
    router
        .route(&request)
        .unwrap_or_else(|error: actions::Error| {
            tracing::error!(
                "{} could not render error: {error:?}",
                request.uri().path()
            );
            error.render(request.uri().path(), &base_templates())
        })
}

/// Route requests to the right actions
pub struct Router<S: Source + Sync + 'static> {
    /// Configured rules
    config: SourcedConfiguration<S>,

    /// Manage template registries
    manager: TemplatesManager,
}

impl<S: Source + Sync + 'static> Router<S> {
    /// Create a router from a [`SourcedConfiguration`].
    ///
    /// # Errors
    ///
    /// Returns an error if there is a problem loading templates.
    #[must_use]
    pub fn from_configuration(config: SourcedConfiguration<S>) -> Self {
        Self { config, manager: TemplatesManager::default() }
    }

    /// Route a request.
    ///
    /// # Errors
    ///
    /// Returned errors will be converted to appropriate HTTP responses.
    pub fn route(
        &self,
        request: &axum::extract::Request,
    ) -> actions::Result<Response> {
        tracing::trace!("route request: {:?}", request.uri());
        self.config.evaluate(&self.manager, request)
    }
}

impl<S: Source + Sync + fmt::Debug> fmt::Debug for Router<S> {
    fn fmt(&self, f: &mut fmt::Formatter<'_>) -> fmt::Result {
        f.debug_struct("Router")
            .field("config", &self.config)
            .field("manager", &self.manager)
            .finish()
    }
}
