//! # Serve pages over HTTP
//!
//! How pages are served are determined by a sequence of rules. See
//! [`riki::rules`][crate::rules].

mod tests;
pub mod util;

use crate::actions::{self, RequestVariables, VariableMap};
use crate::config::SourcedConfiguration;
use crate::config::parser2::GeneratedSource;
use crate::render::{TemplatesManager, base_templates};
use axum::extract::State;
use axum::response::Response;
use std::borrow::Borrow;
use std::fmt;
use std::sync::Arc;
use tower_http::trace::TraceLayer;

// TODO better error handling
//      - Bad page metadata errors should be shown to admin, but not user
//      - dev mode

/// Main entry point for serving over HTTP.
///
/// `configuration` may either be owned, generated by building up action
/// structures, or parsed from `'static` memory.
///
/// # Errors
///
/// May return an error if the server could not start correctly.
pub async fn serve<A: AsRef<str>>(
    configuration: SourcedConfiguration<GeneratedSource<'static>>,
    address: A,
) -> crate::Result<()> {
    let address = address.as_ref();

    axum::serve(
        tokio::net::TcpListener::bind(address)
            .await
            .map_err(|error| crate::Error::BindError {
                source: error,
                address: address.to_owned(),
            })?,
        init_app(configuration),
    )
    .await
    .map_err(crate::Error::Io)
}

/// Initialize the Axum app to be served.
pub fn init_app(
    configuration: SourcedConfiguration<GeneratedSource<'static>>,
) -> axum::Router {
    axum::Router::new()
        .fallback(axum::routing::get(path_handler))
        .with_state(Arc::new(Router::from_configuration(configuration)))
        .layer(TraceLayer::new_for_http())
}

/// Handle all GET requests
pub async fn path_handler(
    State(router): State<Arc<Router>>,
    request: axum::extract::Request,
) -> Response {
    let (parts, _body) = request.into_parts();
    router
        .route(&parts)
        .await
        .unwrap_or_else(|error: actions::Error| {
            tracing::error!(
                "{} could not render error: {error:?}",
                parts.uri.path()
            );
            error.render(parts.uri.path(), &base_templates())
        })
}

/// Route requests to the right actions
pub struct Router {
    /// Configured rules
    config: SourcedConfiguration<GeneratedSource<'static>>,

    /// Manage template registries
    manager: TemplatesManager,
}

impl Router {
    /// Create a router from a [`SourcedConfiguration`].
    ///
    /// # Errors
    ///
    /// Returns an error if there is a problem loading templates.
    #[must_use]
    pub fn from_configuration(
        config: SourcedConfiguration<GeneratedSource<'static>>,
    ) -> Self {
        Self { config, manager: TemplatesManager::default() }
    }

    /// Route a request.
    ///
    /// # Errors
    ///
    /// Returned errors will be converted to appropriate HTTP responses.
    #[expect(
        clippy::unused_async,
        reason = "Required by Axum handler signature"
    )]
    pub async fn route(
        &self,
        parts: &http::request::Parts,
    ) -> actions::Result<Response> {
        tracing::trace!("route request: {:?}", parts.uri);

        // This errors if clean_path() failed, which should never happen.
        // FIXME? move clean_path() out for explicit error handling?
        let variables = RequestVariables::new(parts)?;

        match (|| {
            for rule in self.config.matches(&variables.clean_path()) {
                // FIXME &variables instead of clone()
                match rule.evaluate(&self.manager, variables.clone()) {
                    Err(actions::Error::NotFound) => (), // skip
                    other => return other,
                }
            }
            Err(actions::Error::NotFound)
        })() {
            Ok(response) => Ok(response),
            Err(error) => {
                tracing::trace!("error returned from rules: {error:?}");
                if let Some(rule) =
                    self.config.last_matching(&variables.clean_path())
                {
                    let templates_path =
                        rule.settings.templates.path_content(&variables);
                    // Error: loading templates (no dir, bad template?)
                    let tpls =
                        self.manager.templates_for_directory(templates_path)?;
                    Ok(error.render(variables.request_path().borrow(), &tpls))
                } else {
                    // Use default templates to render error.
                    Err(error)
                }
            }
        }
    }
}

// Implement manually for future generics that might not be `fmt::Debug`.
impl fmt::Debug for Router {
    fn fmt(&self, f: &mut fmt::Formatter<'_>) -> fmt::Result {
        f.debug_struct("Router")
            .field("config", &self.config)
            .field("manager", &self.manager)
            .finish()
    }
}
