//! # Serve pages over HTTP
//!
//! How pages are served are determined by a sequence of rules. See
//! [`riki::rules`][crate::rules].

mod tests;
pub mod util;

use axum::extract::State;
use axum::response::Response;
use riki_actions::{self as actions, RequestVariables, VariableMap};
use riki_config::SourcedConfiguration;
use riki_config::parser2::Source;
use riki_render::{TemplatesManager, base_templates};
use std::borrow::Borrow;
use std::fmt;
use std::sync::Arc;
use tower_http::trace::TraceLayer;

// TODO better error handling
//      - Bad page metadata errors should be shown to admin, but not user
//      - dev mode

/// Main entry point for serving over HTTP.
///
/// `configuration` may either be owned, generated by building up action
/// structures, or parsed from `'static` memory.
///
/// # Errors
///
/// May return an error if the server could not start correctly.
pub async fn serve<S: Source + Sync, A: AsRef<str>>(
    configuration: SourcedConfiguration<S>,
    address: A,
) -> crate::Result<()> {
    let address = address.as_ref();

    axum::serve(
        tokio::net::TcpListener::bind(address)
            .await
            .map_err(|error| crate::Error::BindError {
                source: error,
                address: address.to_owned(),
            })?,
        init_app(configuration),
    )
    .await
    .map_err(crate::Error::Io)
}

/// Initialize the Axum app to be served.
pub fn init_app<S: Source + Sync>(
    configuration: SourcedConfiguration<S>,
) -> axum::Router {
    axum::Router::new()
        .fallback(axum::routing::get(get_handler))
        .with_state(Arc::new(Router::from_configuration(configuration)))
        .layer(TraceLayer::new_for_http())
}

/// Handle all GET requests
async fn get_handler<S: Source + Sync>(
    State(router): State<Arc<Router<S>>>,
    request: axum::extract::Request,
) -> Response {
    router
        .route(&request)
        .unwrap_or_else(|error: actions::Error| {
            tracing::error!(
                "{} could not render error: {error:?}",
                request.uri().path()
            );
            error.render(request.uri().path(), &base_templates())
        })
}

/// Route requests to the right actions
pub struct Router<S: Source + Sync + 'static> {
    /// Configured rules
    config: SourcedConfiguration<S>,

    /// Manage template registries
    manager: TemplatesManager,
}

impl<S: Source + Sync + 'static> Router<S> {
    /// Create a router from a [`SourcedConfiguration`].
    ///
    /// # Errors
    ///
    /// Returns an error if there is a problem loading templates.
    #[must_use]
    pub fn from_configuration(config: SourcedConfiguration<S>) -> Self {
        Self { config, manager: TemplatesManager::default() }
    }

    /// Route a request.
    ///
    /// # Errors
    ///
    /// Returned errors will be converted to appropriate HTTP responses.
    pub fn route(
        &self,
        request: &axum::extract::Request,
    ) -> actions::Result<Response> {
        tracing::trace!("route request: {:?}", request.uri());

        // Returns an error if `clean_path()` fails, which should only happen if
        // the client makes a bad request.
        let variables = RequestVariables::new(request)?;

        match (|| {
            for rule in self.config.matches(&variables.clean_path()) {
                // FIXME &variables instead of clone()
                match rule.evaluate(&self.manager, variables.clone()) {
                    Err(actions::Error::NotFound) => (), // skip
                    other => return other,
                }
            }
            Err(actions::Error::NotFound)
        })() {
            Ok(response) => Ok(response),
            Err(error) => {
                tracing::trace!("error returned from rules: {error:?}");
                if let Some(rule) =
                    self.config.last_matching(&variables.clean_path())
                {
                    let templates_path =
                        rule.settings.templates.path_content(&variables);
                    // Error: loading templates (no dir, bad template?)
                    let tpls = self
                        .manager
                        .templates_for_directory(templates_path)
                        .map_err(|e| {
                            actions::Error::InternalString(e.to_string())
                        })?;
                    Ok(error.render(variables.request_path().borrow(), &tpls))
                } else {
                    // Use default templates to render error.
                    Err(error)
                }
            }
        }
    }
}

impl<S: Source + Sync + fmt::Debug> fmt::Debug for Router<S> {
    fn fmt(&self, f: &mut fmt::Formatter<'_>) -> fmt::Result {
        f.debug_struct("Router")
            .field("config", &self.config)
            .field("manager", &self.manager)
            .finish()
    }
}
