//! The types that represent the actual configuration

mod glob;
mod path;
mod string;
pub use glob::*;
pub use path::*;
pub use string::*;

use super::errors::{ParseError, ParseResult, SpannedErrors};
use super::parser2::{Identifier, MatcherStack, Value};
use globset::{GlobSet, GlobSetBuilder};
use std::env;

/// An entire configuration
#[derive(Clone, Debug)]
pub struct Configuration<'src> {
    /// Matcher to determine which rules to apply.
    globset: GlobSet,

    /// All the rules in the configuration.
    rules: Vec<ConfigRule<'src>>,
}

impl<'src> Configuration<'src> {
    /// Get all the rules.
    #[must_use]
    pub fn rules(&self) -> &[ConfigRule<'src>] {
        &self.rules
    }

    /// Get matching rules for a path.
    #[must_use]
    pub fn matches(&self, path: &str) -> Vec<&ConfigRule<'src>> {
        self.globset
            .matches(path)
            .into_iter()
            .map(|i| &self.rules[i])
            .collect()
    }
}

/// Build a configuration from rules
#[derive(Clone, Debug)]
pub struct ConfigurationBuilder<'src> {
    /// Builder for the final `GlobSet`.
    globset_builder: GlobSetBuilder,

    /// All the rules in the configuration.
    rules: Vec<ConfigRule<'src>>,
}

impl Default for ConfigurationBuilder<'_> {
    fn default() -> Self {
        Self::new()
    }
}

impl<'src> ConfigurationBuilder<'src> {
    /// Create an empty `ConfigurationBuilder`.
    #[must_use]
    pub fn new() -> Self {
        Self { globset_builder: GlobSetBuilder::new(), rules: Vec::new() }
    }

    /// Add a rule.
    ///
    /// # Errors
    ///
    /// Returns an error if there is a problem creating a [`globset::Glob`] from
    /// the rule’s matchers.
    pub fn add(&mut self, rule: ConfigRule<'src>) -> ParseResult<'src, ()> {
        self.globset_builder.add(rule.matcher.as_glob()?);
        self.rules.push(rule);
        Ok(())
    }

    /// Build a [`Configuration`].
    ///
    /// # Errors
    ///
    /// Returns an error if there is a problem creating a [`GlobSet`] from all
    /// the rule matchers.
    pub fn build(self) -> ParseResult<'src, Configuration<'src>> {
        let Self { globset_builder, rules } = self;
        Ok(Configuration {
            globset: globset_builder.build().map_err(|error| {
                ParseError::BuildingGlobSet(error).without_spans().plural()
            })?,
            rules,
        })
    }
}

/// A rule generated by a configuration file
#[derive(Clone, Debug)]
pub struct ConfigRule<'src> {
    /// Match a request.
    pub matcher: MatcherStack<'src>,

    /// Settings from configuration, e.g. the root directory.
    pub settings: ConfigSettings<'src>,

    /// Action to take in response to a request.
    pub action: Value<'src>,
}

impl ConfigRule<'_> {
    /// Return the canonical representation of this rule
    #[must_use]
    pub fn canonical(&self) -> String {
        format!("{} {}", self.matcher.canonical(), self.action.canonical())
    }
}

/// Settings from configuration.
///
/// For example, `root = /srv`.
#[derive(Clone, Debug, Eq, PartialEq)]
pub struct ConfigSettings<'src> {
    /// The root directory to search relative to.
    pub root: ParsedPath<'src>,

    /// Template directory.
    pub templates: ParsedPath<'src>,
}

impl<'src> ConfigSettings<'src> {
    /// Apply a setting.
    ///
    /// # Errors
    ///
    /// Returns [`ParseError`]s if there are problems joining paths or if `name`
    /// or `value` are invalid.
    pub fn apply(
        &mut self,
        name: &Identifier<'src>,
        value: Value<'src>,
    ) -> Result<(), SpannedErrors<'src>> {
        match (name.0, value) {
            ("root", Value::Literal(value)) => {
                self.root.push(&value.into());
                Ok(())
            }
            ("templates", Value::Literal(value)) => {
                self.templates = self.root.join(&value.into());
                Ok(())
            }
            ("root" | "templates", Value::Function(function)) => {
                Err(ParseError::SettingDoesNotAcceptFunction(name.0)
                    .spanned_s((name.0, function.span().clone())))
            }
            (_, _) => {
                Err(ParseError::UnknownSettingName(name.0).spanned_s(name.0))
            }
        }
    }

    /// Generate a canonical version of these settings.
    #[must_use]
    pub fn canonical(&self, matcher: &str) -> Vec<String> {
        vec![
            format!(r"{matcher} root = {}", self.root.canonical()),
            format!(r"{matcher} templates = {}", self.templates.canonical()),
        ]
    }
}

impl Default for ConfigSettings<'_> {
    /// Default settings.
    ///
    ///   * `root`: `.`
    ///   * `templates`: `./templates`
    fn default() -> Self {
        let root: ParsedPath<'_> =
            env::current_dir().unwrap_or_default().into();
        let templates = root.join(&"templates".into());
        Self { root, templates }
    }
}

#[cfg(test)]
mod tests {
    use super::*;
    use crate::actions::StaticVariables;
    use assert2::check;
    use globset::Glob;
    use std::path::PathBuf;

    fn into_glob<'a, I: IntoIterator<Item = &'a str>>(
        globs: I,
    ) -> ParseResult<'a, Glob> {
        let stack = MatcherStack::from_glob_strs(globs);
        println!("glob str: {}", stack.as_glob_str());
        stack.as_glob()
    }

    #[test_log::test]
    fn matcher_stack_paths_makes_valid_globs() {
        check!(into_glob([]).is_ok());
        check!(into_glob(["/"]).is_ok());
        check!(into_glob(["/", "/"]).is_ok());
        check!(into_glob(["/", "foobar", "/zz/"]).is_ok());
        check!(into_glob(["/", "/", "/zz"]).is_ok());
        check!(into_glob(["abc", "/", "/zz"]).is_ok());
        check!(into_glob(["abc", "def", "/zz"]).is_ok());
    }

    #[test_log::test]
    fn matcher_stack_globs_makes_valid_globs() {
        check!(into_glob(["*"]).is_ok());
        check!(into_glob(["**/foo"]).is_ok());
        check!(into_glob(["**/**", "foobar"]).is_ok());
        check!(into_glob(["/", "[abc]?", "/zz"]).is_ok());
    }

    #[test_log::test]
    fn match_file_glob() {
        let matcher = into_glob(["/foo/bar.md"]).unwrap().compile_matcher();
        check!(matcher.is_match("/foo/bar.md"));
        check!(matcher.is_match("/foo/bar.md/"));
        check!(matcher.is_match("/foo/bar.md/test"));
    }

    #[test_log::test]
    fn match_dir_glob() {
        let matcher = into_glob(["/foo/"]).unwrap().compile_matcher();
        check!(!matcher.is_match("/foo"));
        check!(matcher.is_match("/foo/"));
        check!(matcher.is_match("/foo/bar.md/test"));
    }

    /// Test variables
    const VARS: StaticVariables = StaticVariables {
        request_path: "/abc/",
        clean_path: "/abc",
        verb: "GET",
        host: "example.com",
    };

    /// Helper to create an absolute `PathBuf`.
    fn pathbuf(path: &str) -> PathBuf {
        PathBuf::from(".")
            .canonicalize()
            .expect("finding current directory")
            .join(path)
    }

    /// Helper to create a `ParsedString` literal.
    fn literal(s: &str) -> Value<'_> {
        Value::Literal(ParsedString::from_literal(s))
    }

    #[test_log::test]
    fn config_settings_apply_relative() {
        let mut settings = ConfigSettings::default();
        settings
            .apply(&Identifier("root"), literal("new/root"))
            .unwrap();
        check!(settings.root.content(&VARS) == pathbuf("./new/root"));
        check!(settings.templates.content(&VARS) == pathbuf("./templates"));

        settings
            .apply(&Identifier("templates"), literal("tpls"))
            .unwrap();
        check!(settings.root.content(&VARS) == pathbuf("./new/root"));
        check!(settings.templates.content(&VARS) == pathbuf("./new/root/tpls"));
    }

    #[test_log::test]
    fn config_settings_apply_relative_parent() {
        let mut settings = ConfigSettings::default();
        settings
            .apply(&Identifier("root"), literal("/root/a/b"))
            .unwrap();
        check!(settings.root.content(&VARS) == pathbuf("/root/a/b"));
        settings
            .apply(&Identifier("root"), literal("../c"))
            .unwrap();
        check!(settings.root.content(&VARS) == pathbuf("/root/a/b/../c"));
    }

    #[test_log::test]
    fn config_settings_apply_absolute() {
        let mut settings = ConfigSettings::default();
        settings
            .apply(&Identifier("root"), literal("/a/b"))
            .unwrap();
        check!(settings.root.content(&VARS) == pathbuf("/a/b"));
        check!(settings.templates.content(&VARS) == pathbuf("./templates"));

        settings
            .apply(&Identifier("templates"), literal("templates"))
            .unwrap();
        check!(settings.root.content(&VARS) == pathbuf("/a/b"));
        check!(settings.templates.content(&VARS) == pathbuf("/a/b/templates"));

        settings
            .apply(&Identifier("templates"), literal("/templates"))
            .unwrap();
        check!(settings.root.content(&VARS) == pathbuf("/a/b"));
        check!(settings.templates.content(&VARS) == pathbuf("/templates"));
    }
}
